#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "[Husky] post-commit"

if [ -e .commit ]
    then
    rm .commit
    echo "Building client..."
    if [ -e client/dist ]
        then
        rm -rf client/dist
    fi
    npm run client

    echo "Saving changes..."
    git add client/dist
    git commit --amend -C HEAD --no-verify
fi
exit
