#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "[Husky] post-commit"

if [ -e .commit ]
    then
    echo "Building client..."
    if [ -e client/dist ]
        then
        rm -rf client/dist
    fi
    npm run client

    echo "Saving changes..."
    git update-index --add client/dist/*
    rm .commit
fi
exit
